Repository arayabrain/barebone-studio, pull requests merged in 2024-12, with the labels that each got.

#486 Workflow実行時のPipelineテスト
  frontend/package.json
  frontend/src/store/slice/Pipeline/Pipeline.test.ts
  frontend/src/store/slice/Pipeline/PipelineSlice.ts
  frontend/src/store/slice/Pipeline/PipelineTestUtils.ts
  frontend/yarn.lock
Labels: testing

#481 登録済みInput画像データのUIからの削除機能
  frontend/package.json
  frontend/src/api/files/Files.ts
  frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
  frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx
  frontend/src/store/slice/FilesTree/FilesTreeAction.ts
  frontend/src/store/slice/FilesTree/FilesTreeSlice.ts
  frontend/yarn.lock
  studio/app/common/routers/files.py
Labels: frontend

#509 Cloud/bugfix/fix cloud startup script
  cloud-startup.sh
Labels: bug
