Repository arayabrain/barebone-studio, pull requests merged in 2025-02, with the labels that each got.

#587 Suite2pをEdit Roiした際にFluoresenceのダイメンションが逆になっている問題対応
  studio/app/optinist/core/edit_ROI/wrappers/suite2p_edit_roi/utils.py
Labels: bug

#612 consistent colour behaviour
  frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
  frontend/src/components/Workspace/Visualize/Plot/TimeSeriesPlot.tsx
Labels: enhancement, frontend

#608 fix heapmap plot to not overlap with title
  frontend/src/components/Workspace/Visualize/Plot/HeatMapPlot.tsx
Labels: enhancement

#586 Feature/fluo_to_hdf5 transpose
  studio/app/optinist/wrappers/optinist/visualize_utils/fluo_from_hdf5.py
  studio/app/optinist/wrappers/optinist/visualize_utils/params/fluo_from_hdf5.yaml
Labels: frontend

#610 Link and QR to bioRxiv paper
  README.md
  docs/_static/paper_QR.png
Labels: documentation
