Repository arayabrain/barebone-studio, pull requests merged in 2025-01, with the labels that each got.

#555 Feature/roi from hdf5 output
  studio/app/optinist/wrappers/optinist/visualize_utils/roi_from_hdf5.py
Labels: frontend

#548 Feature/lccd output type
  docs/specifications/algorithm_nodes.md
  studio/app/optinist/wrappers/lccd/lccd_detection.py
Labels: backend, frontend

#496 [No.203]Workflow を新しいIDでcopy する機能
  frontend/src/api/experiments/Experiments.ts
  frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
  frontend/src/components/Workspace/__tests__/Experiment/ExperimentTable.test.tsx
  frontend/src/store/slice/Experiments/Experiments.test.ts
  frontend/src/store/slice/Experiments/ExperimentsActions.ts
  frontend/src/store/slice/Experiments/ExperimentsSlice.ts
  frontend/yarn.lock
  studio/app/common/core/experiment/experiment_writer.py
  studio/app/common/routers/experiment.py
  studio/app/common/schemas/experiment.py
  studio/app/optinist/wrappers/caiman/motion_correction.py
Labels: enhancement

#564 Feature/cell numbering
  frontend/src/components/Workspace/Visualize/Editor/ImageItemEditor.tsx
  frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
  frontend/src/components/Workspace/Visualize/Plot/RoiPlot.tsx
  frontend/src/store/slice/VisualizeItem/VisualizeItemSelectors.ts
  frontend/src/store/slice/VisualizeItem/VisualizeItemSlice.ts
  frontend/src/store/slice/VisualizeItem/VisualizeItemType.ts
  studio/app/optinist/wrappers/caiman/cnmf.py
Labels: enhancement, frontend
